name: Sync master to public repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Push master to public repo
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://$TOKEN@github.com/psysuite/psysuitecore-public.git
          git push public master:master --force-with-lease
